CREATE TABLE accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX accounts_username_normalized_unique
ON accounts (
  regexp_replace(
    lower(username),
    '[[:space:]]+',
    '',
    'g'
  )
);

CREATE TABLE households (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE account_households (
  account_id BIGINT NOT NULL
    REFERENCES accounts(id)
    ON DELETE CASCADE,

  household_id BIGINT NOT NULL
    REFERENCES households(id)
    ON DELETE CASCADE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (
    account_id,
    household_id
  )
);

CREATE INDEX account_households_household_id_idx
ON account_households (household_id);

CREATE TABLE household_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  household_id BIGINT NOT NULL
    REFERENCES households(id)
    ON DELETE RESTRICT,

  full_name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  dietary_restrictions TEXT,

  member_role TEXT NOT NULL
    CHECK (
      member_role IN (
        'primary',
        'adult',
        'child'
      )
    ),

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX household_members_household_id_idx
ON household_members (household_id);

CREATE UNIQUE INDEX household_members_one_primary
ON household_members (household_id)
WHERE member_role = 'primary';

CREATE FUNCTION appoponi_assert_household_primary(
  target_household_id BIGINT
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
  member_count BIGINT;
  primary_count BIGINT;
BEGIN
  SELECT
    COUNT(*),
    COUNT(*) FILTER (
      WHERE member_role = 'primary'
    )
  INTO
    member_count,
    primary_count
  FROM household_members
  WHERE household_id = target_household_id;

  IF member_count > 0
     AND primary_count <> 1
  THEN
    RAISE EXCEPTION
      'HOUSEHOLD_PRIMARY_REQUIRED';
  END IF;
END;
$$;

CREATE FUNCTION appoponi_enforce_household_primary()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    PERFORM appoponi_assert_household_primary(
      NEW.household_id
    );

  ELSIF TG_OP = 'DELETE' THEN
    PERFORM appoponi_assert_household_primary(
      OLD.household_id
    );

  ELSE
    PERFORM appoponi_assert_household_primary(
      NEW.household_id
    );

    IF OLD.household_id IS DISTINCT FROM NEW.household_id THEN
      PERFORM appoponi_assert_household_primary(
        OLD.household_id
      );
    END IF;
  END IF;

  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER household_members_primary_required
AFTER INSERT OR UPDATE OR DELETE
ON household_members
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION appoponi_enforce_household_primary();

CREATE TABLE staff_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  account_id BIGINT UNIQUE
    REFERENCES accounts(id)
    ON DELETE SET NULL,

  full_name TEXT NOT NULL,
  email TEXT,
  phone TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
