/* ============================================================
   APPONONI — CANONICAL DATABASE
   One household login account -> household member profiles.
   Staff/admin accounts remain accounts with staff profiles.
   ============================================================ */


/* ============================================================
   ACCOUNTS + PEOPLE
   ============================================================ */

CREATE TABLE accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  username TEXT NOT NULL,
  password_hash TEXT NOT NULL,

  account_type TEXT NOT NULL
    CHECK (
      account_type IN (
        'member',
        'staff',
        'admin'
      )
    ),

  must_change_password BOOLEAN NOT NULL DEFAULT TRUE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX accounts_username_normalized_unique
ON accounts (
  regexp_replace(
    lower(username),
    '[[:space:]]+',
    '',
    'g'
  )
);


CREATE TABLE household_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  account_id BIGINT NOT NULL
    REFERENCES accounts(id),

  full_name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  dietary_restrictions TEXT,

  member_role TEXT NOT NULL
    CHECK (
      member_role IN (
        'primary',
        'adult',
        'child'
      )
    ),

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX household_members_account_id_idx
ON household_members (account_id);

CREATE UNIQUE INDEX household_members_one_primary
ON household_members (account_id)
WHERE member_role = 'primary';


CREATE TABLE staff_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  account_id BIGINT UNIQUE
    REFERENCES accounts(id),

  full_name TEXT NOT NULL,
  email TEXT,
  phone TEXT,

  role TEXT NOT NULL
    CHECK (
      role IN (
        'staff',
        'manager'
      )
    ),

  babysitting_eligible BOOLEAN NOT NULL DEFAULT FALSE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


/* ============================================================
   CAMP AREAS + STAFF CAPABILITIES
   ============================================================ */

CREATE TABLE areas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name TEXT UNIQUE NOT NULL,

  map_x REAL
    CHECK (
      map_x IS NULL
      OR map_x BETWEEN 0 AND 1
    ),

  map_y REAL
    CHECK (
      map_y IS NULL
      OR map_y BETWEEN 0 AND 1
    ),

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE staff_member_areas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  staff_member_id BIGINT NOT NULL
    REFERENCES staff_members(id),

  area_id BIGINT NOT NULL
    REFERENCES areas(id),

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (
    staff_member_id,
    area_id
  )
);


CREATE TABLE qualifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name TEXT UNIQUE NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE staff_qualifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  staff_member_id BIGINT NOT NULL
    REFERENCES staff_members(id),

  qualification_id BIGINT NOT NULL
    REFERENCES qualifications(id),

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (
    staff_member_id,
    qualification_id
  )
);


/* ============================================================
   EVENTS
   ============================================================ */

CREATE TABLE event_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name TEXT UNIQUE NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO event_types (name)
VALUES
  ('Family Camp'),
  ('Wedding'),
  ('Retreat'),
  ('Reunion'),
  ('Corporate'),
  ('Other');


CREATE TABLE event_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name TEXT UNIQUE NOT NULL,

  event_type_id BIGINT NOT NULL
    REFERENCES event_types(id),

  definition JSONB NOT NULL DEFAULT '{}'::jsonb,

  active BOOLEAN NOT NULL DEFAULT TRUE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name TEXT NOT NULL,

  event_type_id BIGINT NOT NULL
    REFERENCES event_types(id),

  template_id BIGINT
    REFERENCES event_templates(id),

  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,

  booked_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CHECK (ends_at > starts_at)
);


CREATE TABLE event_type_others (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  event_id BIGINT UNIQUE NOT NULL
    REFERENCES events(id),

  value TEXT NOT NULL,
  reason TEXT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


/* ============================================================
   ACTIVITIES
   ============================================================ */

CREATE TABLE activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name TEXT UNIQUE NOT NULL,

  area_id BIGINT NOT NULL
    REFERENCES areas(id),

  setting TEXT NOT NULL
    CHECK (
      setting IN (
        'inside',
        'outside',
        'other'
      )
    ),

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE activity_others (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  activity_id BIGINT UNIQUE NOT NULL
    REFERENCES activities(id),

  value TEXT NOT NULL,
  reason TEXT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE activity_qualifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  activity_id BIGINT NOT NULL
    REFERENCES activities(id),

  qualification_id BIGINT NOT NULL
    REFERENCES qualifications(id),

  required_staff_count INTEGER NOT NULL DEFAULT 1
    CHECK (required_staff_count > 0),

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (
    activity_id,
    qualification_id
  )
);


CREATE TABLE event_activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  event_id BIGINT NOT NULL
    REFERENCES events(id),

  activity_id BIGINT NOT NULL
    REFERENCES activities(id),

  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,

  capacity INTEGER
    CHECK (
      capacity IS NULL
      OR capacity > 0
    ),

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CHECK (ends_at > starts_at)
);


CREATE INDEX event_activities_event_time_idx
ON event_activities (
  event_id,
  starts_at,
  ends_at
);


CREATE TABLE event_activity_staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  event_activity_id BIGINT NOT NULL
    REFERENCES event_activities(id),

  staff_member_id BIGINT NOT NULL
    REFERENCES staff_members(id),

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (
    event_activity_id,
    staff_member_id
  )
);


/* ============================================================
   CABINS + EVENT REGISTRATION
   ============================================================ */

CREATE TABLE cabins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name TEXT UNIQUE NOT NULL,

  area_id BIGINT
    REFERENCES areas(id),

  map_x REAL
    CHECK (
      map_x IS NULL
      OR map_x BETWEEN 0 AND 1
    ),

  map_y REAL
    CHECK (
      map_y IS NULL
      OR map_y BETWEEN 0 AND 1
    ),

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE event_registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  account_id BIGINT NOT NULL
    REFERENCES accounts(id),

  event_id BIGINT NOT NULL
    REFERENCES events(id),

  spots_paid_for INTEGER NOT NULL
    CHECK (spots_paid_for > 0),

  cabin_id BIGINT
    REFERENCES cabins(id),

  share_cabin_publicly BOOLEAN NOT NULL DEFAULT FALSE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (
    account_id,
    event_id
  )
);


CREATE TABLE member_attendees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  member_id BIGINT NOT NULL
    REFERENCES household_members(id),

  event_id BIGINT NOT NULL
    REFERENCES events(id),

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (
    member_id,
    event_id
  )
);


CREATE TABLE event_activity_signups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  event_activity_id BIGINT NOT NULL
    REFERENCES event_activities(id),

  member_attendee_id BIGINT NOT NULL
    REFERENCES member_attendees(id),

  checked_in_at TIMESTAMPTZ,
  checked_out_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (
    event_activity_id,
    member_attendee_id
  ),

  CHECK (
    checked_out_at IS NULL
    OR (
      checked_in_at IS NOT NULL
      AND checked_out_at >= checked_in_at
    )
  )
);


/* ============================================================
   MEALS + SIMPLE REUSABLE MENUS
   Deep UMO is intentionally NOT defined here.
   ============================================================ */

CREATE TABLE meal_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name TEXT UNIQUE NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO meal_types (name)
VALUES
  ('Breakfast'),
  ('Brunch'),
  ('Lunch'),
  ('Dinner'),
  ('Reception'),
  ('Cocktail'),
  ('Special');


CREATE TABLE meal_menus (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name TEXT UNIQUE NOT NULL,
  description TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE meal_menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  menu_id BIGINT NOT NULL
    REFERENCES meal_menus(id),

  name TEXT NOT NULL,
  description TEXT,
  dietary_notes TEXT,

  sort_order INTEGER NOT NULL DEFAULT 0,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE event_meals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  event_id BIGINT NOT NULL
    REFERENCES events(id),

  meal_type_id BIGINT NOT NULL
    REFERENCES meal_types(id),

  menu_id BIGINT
    REFERENCES meal_menus(id),

  title TEXT,
  notes TEXT,

  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CHECK (ends_at > starts_at),

  UNIQUE (
    event_id,
    meal_type_id,
    starts_at
  )
);


/* ============================================================
   BABYSITTING
   ============================================================ */

CREATE TABLE babysitting_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  event_registration_id BIGINT NOT NULL
    REFERENCES event_registrations(id),

  sitter_staff_member_id BIGINT
    REFERENCES staff_members(id),

  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,

  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (
      status IN (
        'pending',
        'confirmed',
        'completed',
        'cancelled'
      )
    ),

  notes TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CHECK (ends_at > starts_at)
);


CREATE TABLE babysitting_request_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  babysitting_request_id BIGINT NOT NULL
    REFERENCES babysitting_requests(id),

  member_id BIGINT NOT NULL
    REFERENCES household_members(id),

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (
    babysitting_request_id,
    member_id
  )
);


/* ============================================================
   AFTER-HOURS FOOD / SNACK SERVICE
   No finance/pricing model is invented here.
   ============================================================ */

CREATE TABLE after_hours_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name TEXT UNIQUE NOT NULL,
  description TEXT,

  available BOOLEAN NOT NULL DEFAULT TRUE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE after_hours_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  event_registration_id BIGINT NOT NULL
    REFERENCES event_registrations(id),

  requested_by_member_id BIGINT
    REFERENCES household_members(id),

  assigned_staff_member_id BIGINT
    REFERENCES staff_members(id),

  fulfillment TEXT NOT NULL
    CHECK (
      fulfillment IN (
        'pickup',
        'delivery'
      )
    ),

  delivery_location TEXT,

  status TEXT NOT NULL DEFAULT 'open'
    CHECK (
      status IN (
        'open',
        'fulfilled',
        'cancelled'
      )
    ),

  notes TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE after_hours_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  order_id BIGINT NOT NULL
    REFERENCES after_hours_orders(id),

  item_id BIGINT NOT NULL
    REFERENCES after_hours_items(id),

  quantity INTEGER NOT NULL DEFAULT 1
    CHECK (quantity > 0),

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (
    order_id,
    item_id
  )
);


/* ============================================================
   NOTIFICATIONS
   ============================================================ */

CREATE TABLE notification_preferences (
  account_id BIGINT PRIMARY KEY
    REFERENCES accounts(id),

  activity_reminders BOOLEAN NOT NULL DEFAULT TRUE,
  meal_reminders BOOLEAN NOT NULL DEFAULT TRUE,
  special_notifications BOOLEAN NOT NULL DEFAULT TRUE,
  general_notifications BOOLEAN NOT NULL DEFAULT TRUE,

  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  account_id BIGINT NOT NULL
    REFERENCES accounts(id),

  event_id BIGINT
    REFERENCES events(id),

  kind TEXT NOT NULL
    CHECK (
      kind IN (
        'activity',
        'meal',
        'special',
        'general'
      )
    ),

  title TEXT NOT NULL,
  body TEXT NOT NULL,

  scheduled_for TIMESTAMPTZ,
  read_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


/* ============================================================
   BUILDER IMPORT STAGING
   raw -> parse -> map -> review -> validate -> commit
   ============================================================ */

CREATE TABLE import_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  source_name TEXT NOT NULL,

  source_type TEXT NOT NULL
    CHECK (
      source_type IN (
        'json',
        'csv',
        'tsv',
        'text',
        'excel',
        'pdf',
        'other'
      )
    ),

  status TEXT NOT NULL DEFAULT 'raw'
    CHECK (
      status IN (
        'raw',
        'parsed',
        'mapped',
        'review',
        'validated',
        'committed',
        'failed'
      )
    ),

  mime_type TEXT,
  source_sha256 TEXT,

  raw_content BYTEA,
  raw_text TEXT,
  parsed_payload JSONB,

  source_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE import_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  import_batch_id BIGINT NOT NULL
    REFERENCES import_batches(id),

  source_index INTEGER NOT NULL,

  raw_record JSONB NOT NULL,
  normalized_record JSONB,

  target_table TEXT,
  mapped_record JSONB,

  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (
      status IN (
        'pending',
        'mapped',
        'validated',
        'committed',
        'skipped',
        'error'
      )
    ),

  validation_errors JSONB,

  committed_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (
    import_batch_id,
    source_index
  )
);


CREATE TABLE import_issues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  import_batch_id BIGINT NOT NULL
    REFERENCES import_batches(id),

  import_record_id BIGINT
    REFERENCES import_records(id),

  issue_type TEXT NOT NULL,

  source_key TEXT,
  source_value JSONB,

  suggested_target TEXT,
  resolution JSONB,

  status TEXT NOT NULL DEFAULT 'open'
    CHECK (
      status IN (
        'open',
        'resolved',
        'ignored'
      )
    ),

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE import_provenance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  import_batch_id BIGINT NOT NULL
    REFERENCES import_batches(id),

  import_record_id BIGINT
    REFERENCES import_records(id),

  target_table TEXT NOT NULL,
  target_row_id TEXT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


/* ============================================================
   ACCOUNT / HOUSEHOLD INTEGRITY
   ============================================================ */

CREATE OR REPLACE FUNCTION appoponi_require_member_account()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  actual_type TEXT;
BEGIN
  SELECT account_type
  INTO actual_type
  FROM accounts
  WHERE id = NEW.account_id;

  IF actual_type IS DISTINCT FROM 'member' THEN
    RAISE EXCEPTION 'MEMBER_ACCOUNT_REQUIRED';
  END IF;

  RETURN NEW;
END;
$$;


CREATE TRIGGER household_members_require_member_account
BEFORE INSERT OR UPDATE OF account_id
ON household_members
FOR EACH ROW
EXECUTE FUNCTION appoponi_require_member_account();


CREATE TRIGGER event_registrations_require_member_account
BEFORE INSERT OR UPDATE OF account_id
ON event_registrations
FOR EACH ROW
EXECUTE FUNCTION appoponi_require_member_account();


CREATE OR REPLACE FUNCTION appoponi_require_staff_account()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  actual_type TEXT;
BEGIN
  IF NEW.account_id IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT account_type
  INTO actual_type
  FROM accounts
  WHERE id = NEW.account_id;

  IF actual_type IS NULL
     OR actual_type NOT IN ('staff', 'admin')
  THEN
    RAISE EXCEPTION 'STAFF_ACCOUNT_REQUIRED';
  END IF;

  RETURN NEW;
END;
$$;


CREATE TRIGGER staff_members_require_staff_account
BEFORE INSERT OR UPDATE OF account_id
ON staff_members
FOR EACH ROW
EXECUTE FUNCTION appoponi_require_staff_account();


CREATE OR REPLACE FUNCTION appoponi_protect_account_type()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.account_type = OLD.account_type THEN
    RETURN NEW;
  END IF;

  IF NEW.account_type <> 'member'
     AND (
       EXISTS (
         SELECT 1
         FROM household_members
         WHERE account_id = OLD.id
       )
       OR EXISTS (
         SELECT 1
         FROM event_registrations
         WHERE account_id = OLD.id
       )
     )
  THEN
    RAISE EXCEPTION 'ACCOUNT_HAS_MEMBER_DATA';
  END IF;

  IF NEW.account_type NOT IN ('staff', 'admin')
     AND EXISTS (
       SELECT 1
       FROM staff_members
       WHERE account_id = OLD.id
     )
  THEN
    RAISE EXCEPTION 'ACCOUNT_HAS_STAFF_PROFILE';
  END IF;

  RETURN NEW;
END;
$$;


CREATE TRIGGER protect_account_type
BEFORE UPDATE OF account_type
ON accounts
FOR EACH ROW
EXECUTE FUNCTION appoponi_protect_account_type();


/* ============================================================
   EXACTLY ONE PRIMARY PROFILE PER POPULATED HOUSEHOLD ACCOUNT
   ============================================================ */

CREATE OR REPLACE FUNCTION appoponi_assert_household_primary(
  target_account_id BIGINT
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
  member_count BIGINT;
  primary_count BIGINT;
BEGIN
  SELECT
    COUNT(*),
    COUNT(*) FILTER (
      WHERE member_role = 'primary'
    )
  INTO
    member_count,
    primary_count
  FROM household_members
  WHERE account_id = target_account_id;

  IF member_count > 0
     AND primary_count <> 1
  THEN
    RAISE EXCEPTION 'HOUSEHOLD_PRIMARY_REQUIRED';
  END IF;
END;
$$;


CREATE OR REPLACE FUNCTION appoponi_enforce_household_primary()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    PERFORM appoponi_assert_household_primary(
      NEW.account_id
    );

  ELSIF TG_OP = 'DELETE' THEN
    PERFORM appoponi_assert_household_primary(
      OLD.account_id
    );

  ELSE
    PERFORM appoponi_assert_household_primary(
      NEW.account_id
    );

    IF OLD.account_id IS DISTINCT FROM NEW.account_id THEN
      PERFORM appoponi_assert_household_primary(
        OLD.account_id
      );
    END IF;
  END IF;

  RETURN NULL;
END;
$$;


CREATE CONSTRAINT TRIGGER household_members_primary_required
AFTER INSERT OR UPDATE OR DELETE
ON household_members
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION appoponi_enforce_household_primary();


/* ============================================================
   EVENT CHILD TIMES MUST FIT INSIDE EVENT
   ============================================================ */

CREATE OR REPLACE FUNCTION appoponi_validate_event_child_time()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  parent_start TIMESTAMPTZ;
  parent_end TIMESTAMPTZ;
BEGIN
  SELECT
    starts_at,
    ends_at
  INTO
    parent_start,
    parent_end
  FROM events
  WHERE id = NEW.event_id;

  IF NEW.starts_at < parent_start
     OR NEW.ends_at > parent_end
  THEN
    RAISE EXCEPTION 'EVENT_TIME_OUTSIDE_EVENT';
  END IF;

  RETURN NEW;
END;
$$;


CREATE TRIGGER event_activities_inside_event
BEFORE INSERT OR UPDATE OF event_id, starts_at, ends_at
ON event_activities
FOR EACH ROW
EXECUTE FUNCTION appoponi_validate_event_child_time();


CREATE TRIGGER event_meals_inside_event
BEFORE INSERT OR UPDATE OF event_id, starts_at, ends_at
ON event_meals
FOR EACH ROW
EXECUTE FUNCTION appoponi_validate_event_child_time();


/* ============================================================
   EVENT REGISTRATION CAPACITY
   ============================================================ */

CREATE OR REPLACE FUNCTION appoponi_enforce_registration_capacity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  household_account_id BIGINT;
  paid_spots INTEGER;
  used_spots INTEGER;
BEGIN
  SELECT account_id
  INTO household_account_id
  FROM household_members
  WHERE id = NEW.member_id;

  PERFORM pg_advisory_xact_lock(
    household_account_id
  );

  SELECT spots_paid_for
  INTO paid_spots
  FROM event_registrations
  WHERE account_id = household_account_id
    AND event_id = NEW.event_id
  FOR UPDATE;

  IF paid_spots IS NULL THEN
    RAISE EXCEPTION 'EVENT_REGISTRATION_REQUIRED';
  END IF;

  SELECT COUNT(*)::INTEGER
  INTO used_spots
  FROM member_attendees ma
  JOIN household_members hm
    ON hm.id = ma.member_id
  WHERE hm.account_id = household_account_id
    AND ma.event_id = NEW.event_id
    AND (
      TG_OP = 'INSERT'
      OR ma.id <> NEW.id
    );

  IF used_spots >= paid_spots THEN
    RAISE EXCEPTION 'EVENT_REGISTRATION_SPOTS_FULL';
  END IF;

  RETURN NEW;
END;
$$;


CREATE TRIGGER member_attendees_registration_capacity
BEFORE INSERT OR UPDATE OF member_id, event_id
ON member_attendees
FOR EACH ROW
EXECUTE FUNCTION appoponi_enforce_registration_capacity();


CREATE OR REPLACE FUNCTION appoponi_protect_registration_capacity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  selected_count INTEGER;
BEGIN
  SELECT COUNT(*)::INTEGER
  INTO selected_count
  FROM member_attendees ma
  JOIN household_members hm
    ON hm.id = ma.member_id
  WHERE hm.account_id = NEW.account_id
    AND ma.event_id = NEW.event_id;

  IF NEW.spots_paid_for < selected_count THEN
    RAISE EXCEPTION
      'EVENT_REGISTRATION_BELOW_SELECTED_ATTENDEES';
  END IF;

  RETURN NEW;
END;
$$;


CREATE TRIGGER event_registrations_capacity_guard
BEFORE UPDATE OF account_id, event_id, spots_paid_for
ON event_registrations
FOR EACH ROW
EXECUTE FUNCTION appoponi_protect_registration_capacity();


/* ============================================================
   MEMBER ACTIVITY SIGNUP RULES
   same event
   no duplicates
   no overlapping activity
   respect activity capacity
   ============================================================ */

CREATE OR REPLACE FUNCTION appoponi_enforce_activity_signup()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  requested_member_id BIGINT;
  attendee_event_id BIGINT;

  requested_event_id BIGINT;
  requested_start TIMESTAMPTZ;
  requested_end TIMESTAMPTZ;
  requested_capacity INTEGER;

  current_signup_id BIGINT;
  signup_count INTEGER;
BEGIN
  IF TG_OP = 'UPDATE' THEN
    current_signup_id := OLD.id;
  ELSE
    current_signup_id := NULL;
  END IF;

  SELECT
    member_id,
    event_id
  INTO
    requested_member_id,
    attendee_event_id
  FROM member_attendees
  WHERE id = NEW.member_attendee_id;

  SELECT
    event_id,
    starts_at,
    ends_at,
    capacity
  INTO
    requested_event_id,
    requested_start,
    requested_end,
    requested_capacity
  FROM event_activities
  WHERE id = NEW.event_activity_id;

  IF attendee_event_id <> requested_event_id THEN
    RAISE EXCEPTION
      'ACTIVITY_SIGNUP_EVENT_MISMATCH';
  END IF;

  PERFORM pg_advisory_xact_lock(
    requested_member_id
  );

  PERFORM pg_advisory_xact_lock(
    NEW.event_activity_id
  );

  IF EXISTS (
    SELECT 1
    FROM event_activity_signups eas
    JOIN member_attendees ma
      ON ma.id = eas.member_attendee_id
    WHERE eas.event_activity_id = NEW.event_activity_id
      AND ma.member_id = requested_member_id
      AND (
        current_signup_id IS NULL
        OR eas.id <> current_signup_id
      )
  ) THEN
    RAISE EXCEPTION
      'ACTIVITY_SIGNUP_DUPLICATE';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM event_activity_signups eas
    JOIN member_attendees ma
      ON ma.id = eas.member_attendee_id
    JOIN event_activities existing_activity
      ON existing_activity.id = eas.event_activity_id
    WHERE ma.member_id = requested_member_id
      AND eas.event_activity_id <> NEW.event_activity_id
      AND (
        current_signup_id IS NULL
        OR eas.id <> current_signup_id
      )
      AND requested_start < existing_activity.ends_at
      AND requested_end > existing_activity.starts_at
  ) THEN
    RAISE EXCEPTION
      'ACTIVITY_TIME_CONFLICT';
  END IF;

  IF requested_capacity IS NOT NULL THEN
    SELECT COUNT(*)::INTEGER
    INTO signup_count
    FROM event_activity_signups
    WHERE event_activity_id = NEW.event_activity_id
      AND (
        current_signup_id IS NULL
        OR id <> current_signup_id
      );

    IF signup_count >= requested_capacity THEN
      RAISE EXCEPTION
        'ACTIVITY_CAPACITY_FULL';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;


CREATE TRIGGER enforce_activity_signup
BEFORE INSERT OR UPDATE
ON event_activity_signups
FOR EACH ROW
EXECUTE FUNCTION appoponi_enforce_activity_signup();


/* ============================================================
   STAFF SCHEDULE CONFLICTS
   ============================================================ */

CREATE OR REPLACE FUNCTION appoponi_enforce_staff_activity_schedule()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  requested_start TIMESTAMPTZ;
  requested_end TIMESTAMPTZ;
  current_assignment_id BIGINT;
BEGIN
  IF TG_OP = 'UPDATE' THEN
    current_assignment_id := OLD.id;
  ELSE
    current_assignment_id := NULL;
  END IF;

  SELECT
    starts_at,
    ends_at
  INTO
    requested_start,
    requested_end
  FROM event_activities
  WHERE id = NEW.event_activity_id;

  PERFORM pg_advisory_xact_lock(
    NEW.staff_member_id
  );

  IF EXISTS (
    SELECT 1
    FROM event_activity_staff eas
    JOIN event_activities ea
      ON ea.id = eas.event_activity_id
    WHERE eas.staff_member_id = NEW.staff_member_id
      AND (
        current_assignment_id IS NULL
        OR eas.id <> current_assignment_id
      )
      AND requested_start < ea.ends_at
      AND requested_end > ea.starts_at
  ) THEN
    RAISE EXCEPTION
      'STAFF_ACTIVITY_TIME_CONFLICT';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM babysitting_requests br
    WHERE br.sitter_staff_member_id = NEW.staff_member_id
      AND br.status = 'confirmed'
      AND requested_start < br.ends_at
      AND requested_end > br.starts_at
  ) THEN
    RAISE EXCEPTION
      'STAFF_BABYSITTING_TIME_CONFLICT';
  END IF;

  RETURN NEW;
END;
$$;


CREATE TRIGGER enforce_staff_activity_schedule
BEFORE INSERT OR UPDATE
ON event_activity_staff
FOR EACH ROW
EXECUTE FUNCTION appoponi_enforce_staff_activity_schedule();


/* ============================================================
   BABYSITTING INTEGRITY
   ============================================================ */

CREATE OR REPLACE FUNCTION appoponi_validate_babysitting_request()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  event_start TIMESTAMPTZ;
  event_end TIMESTAMPTZ;
  sitter_allowed BOOLEAN;
  current_request_id BIGINT;
BEGIN
  SELECT
    e.starts_at,
    e.ends_at
  INTO
    event_start,
    event_end
  FROM event_registrations er
  JOIN events e
    ON e.id = er.event_id
  WHERE er.id = NEW.event_registration_id;

  IF NEW.starts_at < event_start
     OR NEW.ends_at > event_end
  THEN
    RAISE EXCEPTION
      'BABYSITTING_OUTSIDE_EVENT';
  END IF;

  IF NEW.sitter_staff_member_id IS NULL
     OR NEW.status <> 'confirmed'
  THEN
    RETURN NEW;
  END IF;

  SELECT babysitting_eligible
  INTO sitter_allowed
  FROM staff_members
  WHERE id = NEW.sitter_staff_member_id;

  IF sitter_allowed IS DISTINCT FROM TRUE THEN
    RAISE EXCEPTION
      'STAFF_NOT_BABYSITTING_ELIGIBLE';
  END IF;

  IF TG_OP = 'UPDATE' THEN
    current_request_id := OLD.id;
  ELSE
    current_request_id := NULL;
  END IF;

  PERFORM pg_advisory_xact_lock(
    NEW.sitter_staff_member_id
  );

  IF EXISTS (
    SELECT 1
    FROM babysitting_requests br
    WHERE br.sitter_staff_member_id = NEW.sitter_staff_member_id
      AND br.status = 'confirmed'
      AND (
        current_request_id IS NULL
        OR br.id <> current_request_id
      )
      AND NEW.starts_at < br.ends_at
      AND NEW.ends_at > br.starts_at
  ) THEN
    RAISE EXCEPTION
      'BABYSITTING_TIME_CONFLICT';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM event_activity_staff eas
    JOIN event_activities ea
      ON ea.id = eas.event_activity_id
    WHERE eas.staff_member_id = NEW.sitter_staff_member_id
      AND NEW.starts_at < ea.ends_at
      AND NEW.ends_at > ea.starts_at
  ) THEN
    RAISE EXCEPTION
      'STAFF_ACTIVITY_TIME_CONFLICT';
  END IF;

  RETURN NEW;
END;
$$;


CREATE TRIGGER validate_babysitting_request
BEFORE INSERT OR UPDATE
ON babysitting_requests
FOR EACH ROW
EXECUTE FUNCTION appoponi_validate_babysitting_request();


CREATE OR REPLACE FUNCTION appoponi_validate_babysitting_member()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  request_account_id BIGINT;
  member_account_id BIGINT;
BEGIN
  SELECT er.account_id
  INTO request_account_id
  FROM babysitting_requests br
  JOIN event_registrations er
    ON er.id = br.event_registration_id
  WHERE br.id = NEW.babysitting_request_id;

  SELECT account_id
  INTO member_account_id
  FROM household_members
  WHERE id = NEW.member_id;

  IF request_account_id <> member_account_id THEN
    RAISE EXCEPTION
      'BABYSITTING_MEMBER_WRONG_HOUSEHOLD';
  END IF;

  RETURN NEW;
END;
$$;


CREATE TRIGGER validate_babysitting_member
BEFORE INSERT OR UPDATE
ON babysitting_request_members
FOR EACH ROW
EXECUTE FUNCTION appoponi_validate_babysitting_member();


/* ============================================================
   AFTER-HOURS ORDER HOUSEHOLD INTEGRITY
   ============================================================ */

CREATE OR REPLACE FUNCTION appoponi_validate_after_hours_order()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  registration_account_id BIGINT;
  member_account_id BIGINT;
BEGIN
  IF NEW.requested_by_member_id IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT account_id
  INTO registration_account_id
  FROM event_registrations
  WHERE id = NEW.event_registration_id;

  SELECT account_id
  INTO member_account_id
  FROM household_members
  WHERE id = NEW.requested_by_member_id;

  IF registration_account_id <> member_account_id THEN
    RAISE EXCEPTION
      'ORDER_MEMBER_WRONG_HOUSEHOLD';
  END IF;

  RETURN NEW;
END;
$$;


CREATE TRIGGER validate_after_hours_order
BEFORE INSERT OR UPDATE
ON after_hours_orders
FOR EACH ROW
EXECUTE FUNCTION appoponi_validate_after_hours_order();


/* ============================================================
   AUTOMATIC UPDATED_AT
   ============================================================ */

CREATE OR REPLACE FUNCTION appoponi_touch_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;


DO $$
DECLARE
  target_table TEXT;
BEGIN
  FOR target_table IN
    SELECT DISTINCT table_name
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND column_name = 'updated_at'
  LOOP
    EXECUTE format(
      'CREATE TRIGGER touch_updated_at
       BEFORE UPDATE ON %I
       FOR EACH ROW
       EXECUTE FUNCTION appoponi_touch_updated_at()',
      target_table
    );
  END LOOP;
END;
$$;


/* ============================================================
   GLOBAL IMMUTABLE AUDIT LOG
   ============================================================ */

CREATE TABLE audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  table_name TEXT NOT NULL,
  row_id TEXT NOT NULL,

  action TEXT NOT NULL
    CHECK (
      action IN (
        'INSERT',
        'UPDATE',
        'DELETE'
      )
    ),

  old_values JSONB,
  new_values JSONB,

  actor_account_id BIGINT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE OR REPLACE FUNCTION appoponi_audit_row_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  actor_text TEXT;
  actor_id BIGINT;
  row_json JSONB;
  changed_row_id TEXT;
BEGIN
  actor_text :=
    current_setting(
      'appoponi.actor_account_id',
      true
    );

  IF actor_text IS NOT NULL
     AND actor_text ~ '^[0-9]+$'
  THEN
    actor_id := actor_text::BIGINT;
  ELSE
    actor_id := NULL;
  END IF;

  IF TG_OP = 'DELETE' THEN
    row_json := to_jsonb(OLD);
  ELSE
    row_json := to_jsonb(NEW);
  END IF;

  changed_row_id := COALESCE(
    row_json->>'id',
    row_json->>'account_id',
    row_json->>'name',
    'unknown'
  );

  INSERT INTO audit_log (
    table_name,
    row_id,
    action,
    old_values,
    new_values,
    actor_account_id
  )
  VALUES (
    TG_TABLE_NAME,
    changed_row_id,
    TG_OP,
    CASE
      WHEN TG_OP IN ('UPDATE', 'DELETE')
      THEN to_jsonb(OLD)
      ELSE NULL
    END,
    CASE
      WHEN TG_OP IN ('INSERT', 'UPDATE')
      THEN to_jsonb(NEW)
      ELSE NULL
    END,
    actor_id
  );

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;

  RETURN NEW;
END;
$$;


DO $$
DECLARE
  target_table TEXT;
BEGIN
  FOR target_table IN
    SELECT tablename
    FROM pg_tables
    WHERE schemaname = 'public'
      AND tablename NOT IN (
        'audit_log',
        'appoponi_migrations'
      )
  LOOP
    EXECUTE format(
      'CREATE TRIGGER audit_row_change
       AFTER INSERT OR UPDATE OR DELETE ON %I
       FOR EACH ROW
       EXECUTE FUNCTION appoponi_audit_row_change()',
      target_table
    );
  END LOOP;
END;
$$;


CREATE OR REPLACE FUNCTION appoponi_prevent_audit_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION
    'audit_log is append-only';
END;
$$;


CREATE TRIGGER audit_log_no_update_delete
BEFORE UPDATE OR DELETE
ON audit_log
FOR EACH ROW
EXECUTE FUNCTION appoponi_prevent_audit_mutation();


CREATE TRIGGER audit_log_no_truncate
BEFORE TRUNCATE
ON audit_log
FOR EACH STATEMENT
EXECUTE FUNCTION appoponi_prevent_audit_mutation();
