/* ============================================================
   REUSABLE MEAL ITEM LIBRARY

   meal_items owns food identity.
   meal_menu_items is composition only: which reusable item is
   used by which menu, on which weekday / meal service.
   ============================================================ */

CREATE TABLE meal_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name TEXT NOT NULL,
  description TEXT,
  dietary_notes TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX meal_items_identity_unique
  ON meal_items (
    LOWER(name),
    COALESCE(LOWER(description), ''),
    COALESCE(LOWER(dietary_notes), '')
  );

ALTER TABLE meal_menu_items
  ADD COLUMN item_id BIGINT
    REFERENCES meal_items(id);

INSERT INTO meal_items (
  name,
  description,
  dietary_notes
)
SELECT DISTINCT ON (
  LOWER(name),
  COALESCE(LOWER(description), ''),
  COALESCE(LOWER(dietary_notes), '')
)
  name,
  description,
  dietary_notes
FROM meal_menu_items
ORDER BY
  LOWER(name),
  COALESCE(LOWER(description), ''),
  COALESCE(LOWER(dietary_notes), ''),
  id;

UPDATE meal_menu_items mmi
SET item_id = mi.id
FROM meal_items mi
WHERE LOWER(mi.name) = LOWER(mmi.name)
  AND COALESCE(LOWER(mi.description), '') =
      COALESCE(LOWER(mmi.description), '')
  AND COALESCE(LOWER(mi.dietary_notes), '') =
      COALESCE(LOWER(mmi.dietary_notes), '');

ALTER TABLE meal_menu_items
  ALTER COLUMN item_id SET NOT NULL,
  DROP COLUMN name,
  DROP COLUMN description,
  DROP COLUMN dietary_notes;

CREATE INDEX meal_menu_items_item_idx
  ON meal_menu_items (item_id);

CREATE TRIGGER touch_updated_at
BEFORE UPDATE ON meal_items
FOR EACH ROW
EXECUTE FUNCTION appoponi_touch_updated_at();

CREATE TRIGGER audit_row_change
AFTER INSERT OR UPDATE OR DELETE ON meal_items
FOR EACH ROW
EXECUTE FUNCTION appoponi_audit_row_change();
