/* ============================================================
   EVENT FOOD SERVICE COMPOSITION

   Product truth:
   - meal_items is the one reusable food library
   - reusable menus provide defaults by weekday + meal type
   - each scheduled event meal/service can be customized from
     that same library without changing the reusable menu
   - after-hours offerings use the same meal_items library
   ============================================================ */

CREATE TABLE event_meal_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_meal_id BIGINT NOT NULL
    REFERENCES event_meals(id)
    ON DELETE CASCADE,
  item_id BIGINT NOT NULL
    REFERENCES meal_items(id),
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (event_meal_id, item_id)
);

CREATE INDEX event_meal_items_service_idx
  ON event_meal_items (event_meal_id, sort_order, id);

CREATE TABLE event_after_hours_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL
    REFERENCES events(id)
    ON DELETE CASCADE,
  item_id BIGINT NOT NULL
    REFERENCES meal_items(id),
  sort_order INTEGER NOT NULL DEFAULT 0,
  available BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (event_id, item_id)
);

CREATE INDEX event_after_hours_items_event_idx
  ON event_after_hours_items (event_id, available, sort_order, id);

/* Reuse the permanent food library for the legacy after-hours catalog. */
INSERT INTO meal_items (
  name,
  description,
  dietary_notes
)
SELECT
  ahi.name,
  ahi.description,
  NULL
FROM after_hours_items ahi
WHERE NOT EXISTS (
  SELECT 1
  FROM meal_items mi
  WHERE LOWER(mi.name) = LOWER(ahi.name)
    AND COALESCE(LOWER(mi.description), '') =
        COALESCE(LOWER(ahi.description), '')
    AND COALESCE(LOWER(mi.dietary_notes), '') = ''
);

/* The legacy catalog was global, so preserve it for every existing event. */
INSERT INTO event_after_hours_items (
  event_id,
  item_id,
  sort_order,
  available
)
SELECT
  e.id,
  mi.id,
  ROW_NUMBER() OVER (
    PARTITION BY e.id
    ORDER BY LOWER(ahi.name), ahi.id
  )::INTEGER * 10,
  ahi.available
FROM events e
CROSS JOIN after_hours_items ahi
JOIN meal_items mi
  ON LOWER(mi.name) = LOWER(ahi.name)
 AND COALESCE(LOWER(mi.description), '') =
     COALESCE(LOWER(ahi.description), '')
 AND COALESCE(LOWER(mi.dietary_notes), '') = ''
ON CONFLICT (event_id, item_id)
DO UPDATE SET
  available = EXCLUDED.available;

/* Preserve order history while changing the order line FK to meal_items. */
ALTER TABLE after_hours_order_items
  ADD COLUMN meal_item_id BIGINT
    REFERENCES meal_items(id);

UPDATE after_hours_order_items aoi
SET meal_item_id = mi.id
FROM after_hours_items ahi
JOIN meal_items mi
  ON LOWER(mi.name) = LOWER(ahi.name)
 AND COALESCE(LOWER(mi.description), '') =
     COALESCE(LOWER(ahi.description), '')
 AND COALESCE(LOWER(mi.dietary_notes), '') = ''
WHERE aoi.item_id = ahi.id;

ALTER TABLE after_hours_order_items
  ALTER COLUMN meal_item_id SET NOT NULL,
  DROP CONSTRAINT after_hours_order_items_order_id_item_id_key,
  DROP COLUMN item_id;

ALTER TABLE after_hours_order_items
  RENAME COLUMN meal_item_id TO item_id;

ALTER TABLE after_hours_order_items
  ADD CONSTRAINT after_hours_order_items_order_id_item_id_key
  UNIQUE (order_id, item_id);

DROP TABLE after_hours_items;

CREATE TRIGGER touch_updated_at
BEFORE UPDATE ON event_meal_items
FOR EACH ROW
EXECUTE FUNCTION appoponi_touch_updated_at();

CREATE TRIGGER touch_updated_at
BEFORE UPDATE ON event_after_hours_items
FOR EACH ROW
EXECUTE FUNCTION appoponi_touch_updated_at();

CREATE TRIGGER audit_row_change
AFTER INSERT OR UPDATE OR DELETE ON event_meal_items
FOR EACH ROW
EXECUTE FUNCTION appoponi_audit_row_change();

CREATE TRIGGER audit_row_change
AFTER INSERT OR UPDATE OR DELETE ON event_after_hours_items
FOR EACH ROW
EXECUTE FUNCTION appoponi_audit_row_change();
