/* ============================================================
   STRUCTURED FOOD TAGS

   Product truth:
   - meal_items is the reusable food library
   - tags describe what a food is, not when Camp offers it
   - one food can have many structured tags
   - Breakfast/Lunch/Dinner/Snack/After-hours availability remains
     separate composition/availability data
   ============================================================ */

CREATE TABLE meal_item_tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  item_id BIGINT NOT NULL
    REFERENCES meal_items(id)
    ON DELETE CASCADE,

  tag TEXT NOT NULL
    CHECK (
      tag IN (
        'SNACK',
        'BEVERAGE',
        'ENTREE',
        'SIDE',
        'DESSERT',
        'APPETIZER',
        'SALAD',
        'SOUP',
        'BAKERY',
        'FRUIT',
        'CONDIMENT',
        'VEGETARIAN',
        'VEGAN',
        'GLUTEN_FREE',
        'DAIRY_FREE'
      )
    ),

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (item_id, tag)
);

CREATE INDEX meal_item_tags_tag_item_idx
  ON meal_item_tags (tag, item_id);

CREATE TRIGGER audit_row_change
AFTER INSERT OR UPDATE OR DELETE ON meal_item_tags
FOR EACH ROW
EXECUTE FUNCTION appoponi_audit_row_change();
